project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app_base import views as base_views
from app_course import views as course_views
from app_course_file import views as course_file_views
from app_course_test import views as course_test_views
from app_course_topic import views as course_topic_views
from app_semester import views as semester_views
from app_student_group import views as student_group_views
from app_student_status import views as student_status_views
from app_user import views as user_views

base_namespace = ([
    path('', base_views.IndexPage.as_view(), name='index'),
], 'base')

course_namespace = ([
    path('admin_list/', course_views.admin_list, name='admin_list'),
    path('admin_create/', course_views.admin_form, name='admin_create'),
    path('admin_edit/<int:course_pk>/', course_views.admin_form, name='admin_edit'),
    path('admin_delete/<int:course_pk>/', course_views.admin_delete, name='admin_delete'),
    path('admin_student/', course_views.admin_students, name='admin_student'),  # Don't use this URL
    path('admin_student/<int:semester_pk>/', course_views.admin_students, name='admin_student'),
    path('admin_student/<int:semester_pk>/<int:course_pk>/', course_views.admin_students, name='admin_student'),
    path('teacher_list/', course_views.teacher_list, name='teacher_list'),
    path('teacher_page/<int:course_pk>/', course_views.teacher_page, name='teacher_page'),
    path('student_list/', course_views.student_list, name='student_list'),
    path('student_page/<int:course_pk>/', course_views.student_page, name='student_page'),
], 'course')

course_file_namespace = ([
    path('create/<int:pk>/', course_file_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', course_file_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', course_file_views.Delete.as_view(), name='delete'),
], 'course_file')

course_test_namespace = ([
    path('test/<int:test_pk>/', course_test_views.test_page, name='test_page'),
], 'course_test')

course_topic_namespace = ([
    path('create/<int:course_pk>/', course_topic_views.topic_create, name='create'),
    path('edit/<int:topic_pk>/', course_topic_views.topic_form, name='edit'),
    path('page/<int:topic_pk>/', course_topic_views.topic_page, name='topic_page'),
    path('delete/<int:pk>/', course_topic_views.Delete.as_view(), name='delete'),
], 'course_topic')

semester_namespace = ([
    path('list/', semester_views.semester_list, name='list'),
    path('create/', semester_views.semester_form, name='create'),
    path('edit/<int:semester_pk>/', semester_views.semester_form, name='edit'),
    path('delete/<int:semester_pk>/', semester_views.semester_delete, name='delete'),
], 'semester')

student_group_namespace = ([
    path('list/', student_group_views.group_list, name='list'),
    path('create/', student_group_views.group_form, name='create'),
    path('edit/<int:group_pk>/', student_group_views.group_form, name='edit'),
    path('delete/<int:group_pk>/', student_group_views.group_delete, name='delete'),
], 'student_group')

student_status_namespace = ([
    path('create/<int:pk>/', student_status_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', student_status_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', student_status_views.Delete.as_view(), name='delete'),
], 'student_status')

user_namespace = ([
    path('login/', user_views.LoginPage.as_view(), name='login'),
    path('logout/', user_views.LogoutPage.as_view(), name='logout'),
    path('password/', user_views.PasswordChangePage.as_view(), name='change_password'),
    path('password/<int:user_id>/', user_views.SetPasswordPage.as_view(), name='set_password'),
    path('list/', user_views.List.as_view(), name='list'),
    path('create/', user_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', user_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', user_views.Delete.as_view(), name='delete'),
], 'user')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(base_namespace)),
    path('course/', include(course_namespace)),
    path('course_file/', include(course_file_namespace)),
    path('course_test/', include(course_test_namespace)),
    path('course_topic/', include(course_topic_namespace)),
    path('semester/', include(semester_namespace)),
    path('student_group/', include(student_group_namespace)),
    path('student_status/', include(student_status_namespace)),
    path('user/', include(user_namespace)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_course/models.py
import os

from django.conf import settings
from django.db import models


# TODO: Преподаватель должен иметь возможность добавить файлы к курсу
class Course(models.Model):
    MANDATORY = 1
    OPTIONAL = 2
    COURSE_TYPE = (
        (MANDATORY, 'обязательный'),
        (OPTIONAL, 'курс по выбору'),
    )

    name = models.CharField('наименование', max_length=150)
    semester = models.ForeignKey('app_semester.Semester', on_delete=models.DO_NOTHING, verbose_name='семестр')
    teacher = models.ForeignKey('app_user.User', on_delete=models.DO_NOTHING, related_name='teaching_load',
                                verbose_name='преподаватель')
    course_type = models.IntegerField('тип курса', choices=COURSE_TYPE)
    students = models.ManyToManyField('app_user.User', blank=True, related_name='studied_courses',
                                      verbose_name='студенты')
    lecture_hours = models.IntegerField('часы лекций', blank=True, default=0)
    lab_work_hours = models.IntegerField('часы лаб. работ', blank=True, default=0)
    practice_hours = models.IntegerField('часы практ. работ', blank=True, default=0)
    student_hours = models.IntegerField('часы СРС', blank=True, default=0)
    control_hours = models.IntegerField('часы КСР', blank=True, default=0)
    total_hours = models.IntegerField('часов всего', blank=True, default=0)

    class Meta:
        verbose_name = 'дисциплина'
        verbose_name_plural = 'дисциплины'

    def __str__(self):
        return self.name

    def get_folder(self):
        return os.path.join(settings.MEDIA_ROOT, 'courses', str(self.pk))


class CourseElement(models.Model):
    kind = 'element'

    course = models.ForeignKey('app_course.Course', on_delete=models.CASCADE, verbose_name='курс обучения')
    order = models.IntegerField('порядковый номер')
    name = models.CharField('наименование', max_length=150, unique=True)

    class Meta:
        abstract = True
        ordering = ['order']

    def __str__(self):
        return self.name

app_student_group/models.py
import datetime

from django.db import models
from django.db.models.query import RawQuerySet


class StudentGroup(models.Model):
    BACHELOR = 'B'
    SPECIALIST = 'S'
    MASTER = 'M'
    DEGREE = (
        (BACHELOR, 'бакалавриат'),
        (MASTER, 'магистратура'),
        (SPECIALIST, 'специалитет'),
    )

    FULL_TIME = 'F'
    PART_TIME = 'P'
    FORM = (
        (FULL_TIME, 'очная'),
        (PART_TIME, 'заочная')
    )

    name = models.CharField('наименование', max_length=30)
    year = models.IntegerField('год поступления')
    degree = models.CharField('квалификация', max_length=1, choices=DEGREE)
    form = models.CharField('форма обучения', max_length=1, choices=FORM)
    is_active = models.BooleanField('в процессе обучения', default=False)

    class Meta:
        verbose_name = 'учебная группа'
        verbose_name_plural = 'учебные группы'
        ordering = ['degree', 'year', 'name']

    def __str__(self):
        return self.name

    def get_students(self, date: datetime.date) -> RawQuerySet:
        """Студенты, которые учатся в этом семестре в этой группе"""
        from app_user.models import User
        return User.objects.raw("""
            SELECT
                t_user.id, t_user.username, t_user.first_name, t_user.last_name
            FROM (
                SELECT student_id, MAX(moment) AS moment 
                FROM app_student_status_studentstatus 
                GROUP BY student_id 
                HAVING DATE(moment) <= '%s'
                ) AS t_base 
            LEFT JOIN 
                app_student_status_studentstatus AS t_status 
                ON t_base.student_id = t_status.student_id AND t_base.moment = t_status.moment
            LEFT JOIN 
                app_user_user AS t_user 
                ON t_base.student_id = t_user.id
            WHERE
              t_status.status = 'E' and t_status.student_group_id = '%d'
        """ % (date.isoformat(), self.id))

app_student_group/views.py
from django.contrib.auth.decorators import user_passes_test
from django.forms import ModelForm
from django.shortcuts import render, get_object_or_404, redirect

from app_semester.models import Semester
from app_student_group.models import StudentGroup


class GroupForm(ModelForm):
    class Meta:
        model = StudentGroup
        fields = '__all__'


@user_passes_test(lambda u: u.is_superuser)
def group_list(request):
    return render(request, 'student_group/list.html', {
        'current_list': StudentGroup.objects.filter(is_active=True),
        'archive_list': StudentGroup.objects.filter(is_active=False)
    })


@user_passes_test(lambda u: u.is_superuser)
def group_form(request, group_pk=None):
    group = get_object_or_404(StudentGroup, pk=group_pk) if group_pk else None
    if request.method == 'POST':
        form = GroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
            return redirect('student_group::list')
    else:
        form = GroupForm(instance=group)
    context = {'form': form}
    if group_pk:
        context['semesters'] = Semester.objects.filter(student_group=group)
    return render(request, 'student_group/form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def group_delete(request, group_pk):
    group = get_object_or_404(StudentGroup, pk=group_pk)
    if request.method == 'POST':
        group.delete()
        return redirect('student_group::list')
    return render(request, 'student_group/confirm_delete.html', {'group': group})

app_student_group/templates/student_group/confirm_delete.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Удаление учебной группы</h1>
      <p>Подтвердите удаление учебной группы {{ group }}</p>
      <form method="post">
        {% csrf_token %}
        <input type="submit" name="submit" class="btn btn-danger" value="Удалить">
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function (event) {
        history.back();
      });
    });
  </script>
{% endblock %}

app_student_group/templates/student_group/form.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>
        {% if form.instance.pk %}
          Редактирование учебной группы
        {% else %}
          Создание учебной группы
        {% endif %}
      </h1>

      <h3>{{ form.instance }}</h3>
      <form method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
        <div class="form-row">
          {% form_control form.name "col" %}
          {% form_control form.year "col" %}
          {% form_control form.degree "col" %}
          {% form_control form.form "col" %}
        </div>
        <div class="form-row">
          {% form_check form.is_active "col" %}
        </div>

        <h3>Семестры</h3>
        <table class="table table-hover">
          <thead>
          <tr>
            <th>Семестр</th>
            <th>Теоретическое обучение</th>
            <th>Сессия</th>
            <th><a href="{% url 'semester:create' %}"><i class="fas fa-plus"></i></a></th>
          </tr>
          </thead>
          <tbody>
          {% for s in semesters %}
            <tr>
              <td><a href="{% url 'semester:edit' s.id %}">{{ s.get_year }}, {{ s.get_semester_display }}</a></td>
              <td>{{ s.begin_study|date:"Y.m.d" }} – {{ s.end_study|date:"Y.m.d" }}</td>
              <td>{{ s.begin_exams|date:"Y.m.d" }} – {{ s.end_exams|date:"Y.m.d" }}</td>
              <td><a href="{% url 'semester:delete' s.id %}"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>

        <input type="submit" name="submit" class="btn btn-primary" value="Сохранить">
        {% if form.instance.pk %}
          <a href="{% url 'student_group:delete' form.instance.id %}" class="btn btn-danger" role="button">Удалить</a>
        {% endif %}
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function () {
        history.back();
      });
    });
  </script>
{% endblock %}

app_student_group/templates/student_group/list.html
{% extends 'base/menu.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      {% if current_list %}
        <h1>Текущие учебные группы</h1>
        {% regroup current_list by get_degree_display as grouped_list1 %}
        {% for group1 in grouped_list1 %}
          <h3>{{ group1.grouper|capfirst }}</h3>
          {% regroup group1.list by year as grouped_list2 %}
          {% for group2 in grouped_list2 %}
            <h5>Год поступления: {{ group2.grouper }}</h5>
            <ul>
              {% for sg in group2.list %}
                <li><a href="{% url 'student_group:edit' sg.id %}">{{ sg.name }}</a></li>
              {% endfor %}
            </ul>
          {% endfor %}
        {% endfor %}
      {% endif %}

      {% if archive_list %}
        <h1>Архивные учебные группы</h1>
        {% regroup archive_list by get_degree_display as grouped_list1 %}
        {% for group1 in grouped_list1 %}
          <h3>{{ group1.grouper|capfirst }}</h3>
          {% regroup group1.list by year as grouped_list2 %}
          {% for group2 in grouped_list2 %}
            <h5>Год поступления: {{ group2.grouper }}</h5>
            <ul>
              {% for sg in group2.list %}
                <li><a href="{% url 'student_group:edit' sg.id %}">{{ sg.name }}</a></li>
              {% endfor %}
            </ul>
          {% endfor %}
        {% endfor %}
      {% endif %}

      <a href="{% url 'student_group:create' %}" class="btn btn-primary" role="button">Создать</a>
    </div>
  </div>
{% endblock %}