project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app_base import views as base_views
from app_course import views as course_views
from app_course_file import views as course_file_views
from app_course_test import views as course_test_views
from app_course_topic import views as course_topic_views
from app_semester import views as semester_views
from app_student_group import views as student_group_views
from app_student_status import views as student_status_views
from app_user import views as user_views

base_namespace = ([
    path('', base_views.IndexPage.as_view(), name='index'),
], 'base')

course_namespace = ([
    path('admin_list/', course_views.admin_list, name='admin_list'),
    path('admin_create/', course_views.admin_form, name='admin_create'),
    path('admin_edit/<int:course_pk>/', course_views.admin_form, name='admin_edit'),
    path('admin_delete/<int:course_pk>/', course_views.admin_delete, name='admin_delete'),
    path('admin_student/', course_views.admin_students, name='admin_student'),  # Don't use this URL
    path('admin_student/<int:semester_pk>/', course_views.admin_students, name='admin_student'),
    path('admin_student/<int:semester_pk>/<int:course_pk>/', course_views.admin_students, name='admin_student'),
    path('teacher_list/', course_views.teacher_list, name='teacher_list'),
    path('teacher_page/<int:course_pk>/', course_views.teacher_page, name='teacher_page'),
    path('student_list/', course_views.student_list, name='student_list'),
    path('student_page/<int:course_pk>/', course_views.student_page, name='student_page'),
], 'course')

course_file_namespace = ([
    path('create/<int:pk>/', course_file_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', course_file_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', course_file_views.Delete.as_view(), name='delete'),
], 'course_file')

course_test_namespace = ([
    path('test/<int:test_pk>/', course_test_views.test_page, name='test_page'),
], 'course_test')

course_topic_namespace = ([
    path('create/<int:course_pk>/', course_topic_views.topic_create, name='create'),
    path('edit/<int:topic_pk>/', course_topic_views.topic_form, name='edit'),
    path('page/<int:topic_pk>/', course_topic_views.topic_page, name='topic_page'),
    path('delete/<int:pk>/', course_topic_views.Delete.as_view(), name='delete'),
], 'course_topic')

semester_namespace = ([
    path('list/', semester_views.semester_list, name='list'),
    path('create/', semester_views.semester_form, name='create'),
    path('edit/<int:semester_pk>/', semester_views.semester_form, name='edit'),
    path('delete/<int:semester_pk>/', semester_views.semester_delete, name='delete'),
], 'semester')

student_group_namespace = ([
    path('list/', student_group_views.group_list, name='list'),
    path('create/', student_group_views.group_form, name='create'),
    path('edit/<int:group_pk>/', student_group_views.group_form, name='edit'),
    path('delete/<int:group_pk>/', student_group_views.group_delete, name='delete'),
], 'student_group')

student_status_namespace = ([
    path('create/<int:pk>/', student_status_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', student_status_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', student_status_views.Delete.as_view(), name='delete'),
], 'student_status')

user_namespace = ([
    path('login/', user_views.LoginPage.as_view(), name='login'),
    path('logout/', user_views.LogoutPage.as_view(), name='logout'),
    path('password/', user_views.PasswordChangePage.as_view(), name='change_password'),
    path('password/<int:user_id>/', user_views.SetPasswordPage.as_view(), name='set_password'),
    path('list/', user_views.List.as_view(), name='list'),
    path('create/', user_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', user_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', user_views.Delete.as_view(), name='delete'),
], 'user')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(base_namespace)),
    path('course/', include(course_namespace)),
    path('course_file/', include(course_file_namespace)),
    path('course_test/', include(course_test_namespace)),
    path('course_topic/', include(course_topic_namespace)),
    path('semester/', include(semester_namespace)),
    path('student_group/', include(student_group_namespace)),
    path('student_status/', include(student_status_namespace)),
    path('user/', include(user_namespace)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_course/models.py
import os

from django.conf import settings
from django.db import models


# TODO: Преподаватель должен иметь возможность добавить файлы к курсу
class Course(models.Model):
    MANDATORY = 1
    OPTIONAL = 2
    COURSE_TYPE = (
        (MANDATORY, 'обязательный'),
        (OPTIONAL, 'курс по выбору'),
    )

    name = models.CharField('наименование', max_length=150)
    semester = models.ForeignKey('app_semester.Semester', on_delete=models.DO_NOTHING, verbose_name='семестр')
    teacher = models.ForeignKey('app_user.User', on_delete=models.DO_NOTHING, related_name='teaching_load',
                                verbose_name='преподаватель')
    course_type = models.IntegerField('тип курса', choices=COURSE_TYPE)
    students = models.ManyToManyField('app_user.User', blank=True, related_name='studied_courses',
                                      verbose_name='студенты')
    lecture_hours = models.IntegerField('часы лекций', blank=True, default=0)
    lab_work_hours = models.IntegerField('часы лаб. работ', blank=True, default=0)
    practice_hours = models.IntegerField('часы практ. работ', blank=True, default=0)
    student_hours = models.IntegerField('часы СРС', blank=True, default=0)
    control_hours = models.IntegerField('часы КСР', blank=True, default=0)
    total_hours = models.IntegerField('часов всего', blank=True, default=0)

    class Meta:
        verbose_name = 'дисциплина'
        verbose_name_plural = 'дисциплины'

    def __str__(self):
        return self.name

    def get_folder(self):
        return os.path.join(settings.MEDIA_ROOT, 'courses', str(self.pk))


class CourseElement(models.Model):
    kind = 'element'

    course = models.ForeignKey('app_course.Course', on_delete=models.CASCADE, verbose_name='курс обучения')
    order = models.IntegerField('порядковый номер')
    name = models.CharField('наименование', max_length=150, unique=True)

    class Meta:
        abstract = True
        ordering = ['order']

    def __str__(self):
        return self.name

app_course/views.py
from django.conf import settings
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib.auth.views import redirect_to_login
from django.forms import ModelForm
from django.shortcuts import get_object_or_404, render, redirect

from app_course.models import Course, CourseElement
from app_course_test.models import Test
from app_course_topic.models import Topic
from app_semester.models import Semester


class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = '__all__'


def teacher_required(cls, key='pk'):
    """
    Порождает декоратор для защиты CBV или view-функций от других преподавателей
    :param cls: класс Course или класс-потомок CourseElement
    :param key: имя параметра запроса хранящего идентификатор объекта класса cls
    :return: декоратор
    """
    def decorator(view_func):
        def wrapper(request, *args, **kwargs):
            if request.user.is_staff:
                obj = get_object_or_404(cls, pk=request.resolver_match.kwargs[key])
                if isinstance(obj, Course):
                    if request.user == obj.teacher:
                        return view_func(request, *args, **kwargs)
                elif isinstance(obj, CourseElement):
                    if request.user == obj.course.teacher:
                        return view_func(request, *args, **kwargs)
            return redirect_to_login(request.path, settings.LOGIN_URL, REDIRECT_FIELD_NAME)
        return wrapper
    return decorator


@user_passes_test(lambda u: u.is_superuser)
def admin_list(request):
    return render(request, 'course/list.html', {'course_list': Course.objects.all()})


@user_passes_test(lambda u: u.is_superuser)
def admin_form(request, course_pk=None):
    course = get_object_or_404(Course, pk=course_pk) if course_pk else None
    if request.method == 'POST':
        form = CourseForm(request.POST, instance=course)
        if form.is_valid():
            form.save()
            return redirect('course:admin_list')
    else:
        form = CourseForm(instance=course)
    context = {'form': form}
    if course_pk:
        context['students_available'] = list(course.semester.get_students())
        context['students_selected'] = list(course.students.all())
    return render(request, 'course/form.html', context)


@user_passes_test(lambda u: u.is_superuser)
def admin_delete(request, course_pk=None):
    course = get_object_or_404(Course, pk=course_pk)
    if request.method == 'POST':
        course.delete()
        return redirect('course:admin_list')
    return render(request, 'course/confirm_delete.html', {'course': course})


@user_passes_test(lambda u: u.is_superuser)
def admin_students(request, semester_pk, course_pk=None):
    semester = get_object_or_404(Semester, pk=semester_pk)
    context = {'students_available': list(semester.get_students())}
    if course_pk:
        course = get_object_or_404(Course, pk=course_pk)
        context['students_selected'] = list(course.students.all())
    return render(request, 'course/students.html', context)


@user_passes_test(lambda u: u.is_staff)
def teacher_list(request):
    return render(request, 'course/list_teacher.html', {'teaching_load': request.user.teaching_load.all()})


@user_passes_test(lambda u: u.is_staff)
def teacher_page(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    elements = list(course.topic_set.all()) + list(course.file_set.all())
    return render(request, 'course/detail_teacher.html', {
        'course': course,
        'elements': sorted(elements, key=lambda e: e.order)
    })


@login_required
def student_list(request):
    return render(request, 'course/course_list.html', {'studied_courses': request.user.studied_courses.all()})


@login_required
def student_page(request, course_pk):
    course = get_object_or_404(Course, pk=course_pk)
    topics = list(Topic.objects.filter(course=course))
    tests = list(Test.objects.filter(course=course, user=request.user))
    return render(request, 'course/course_detail.html', {
        'elements': sorted(topics + tests, key=lambda elem: elem.order)
    })

app_course/templates/course/confirm_delete.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Удаление дисциплины</h1>
      <p>Подтвердите удаление дисциплины {{ course }}</p>
      <form method="post">
        {% csrf_token %}
        <input type="submit" name="submit" class="btn btn-danger" value="Удалить">
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function (event) {
        history.back();
      });
    });
  </script>
{% endblock %}

app_course/templates/course/course_detail.html
{% extends 'base/menu.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>{% block title %}{{ course.name }}{% endblock %}</h1>
      <ul>
        {% for e in elements %}
          {% if e.kind == 'topic' %}
            <li><a href="{% url 'course_topic:page' e.id %}">{{ e.code }} {{ e.name }}</a></li>
          {% elif e.kind == 'test' %}
            <li><a href="{% url 'course_test:test_page' e.id %}">{{ e.code }} {{ e.name }}</a></li>
          {% endif %}
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

app_course/templates/course/course_list.html
{% extends 'base/menu.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Изучаемые дисциплины</h1>
      <ul>
        {% for c in studied_courses %}
          <li><a href="{% url 'course:student_page' c.id %}">{{ c.name }}</a></li>
        {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

app_course/templates/course/detail_teacher.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>{{ course.name }}</h1>

      <h3>Элементы курса</h3>

      <table class="table table-hover">
        <thead>
        <tr>
          <th>№ п/п</th>
          <th>Тип</th>
          <th>Наименование</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        {% for e in elements %}
          {% if e|get_class == 'Topic' %}
            <tr>
              <td><a href="{% url 'course_topic:edit' e.id %}">{{ e.order }}</a></td>
              <td><a href="{% url 'course_topic:edit' e.id %}">Тема</a></td>
              <td><a href="{% url 'course_topic:edit' e.id %}">{{ e.name }}</a></td>
              <td><a href="{% url 'course_topic:delete' e.id %}"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
          {% elif e|get_class == 'File' %}
            <tr>
              <td><a href="{% url 'course_file:edit' e.id %}">{{ e.order }}</a></td>
              <td><a href="{% url 'course_file:edit' e.id %}">Файл</a></td>
              <td><a href="{% url 'course_file:edit' e.id %}">{{ e.name }}</a></td>
              <td><a href="{% url 'course_file:delete' e.id %}"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
          {% endif %}
        {% endfor %}
        </tbody>
      </table>

      <a class="btn btn-primary" href="{% url 'course_topic:create' course.id %}">Создать тему</a>
      <a class="btn btn-primary" href="{% url 'course_file:create' course.id %}">Создать файл</a>

    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function () {
        history.back();
      });
    });
  </script>
{% endblock %}

app_course/templates/course/form.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>
        {% if form.instance.pk %}
          Дисциплина {{ form.instance }}
        {% else %}
          Создание дисциплины
        {% endif %}
      </h1>
    </div>
  </div>
  <form method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col">
        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col">
        {% form_control form.name %}
        {% form_control form.semester %}
        {% form_control form.teacher %}
        {% form_control form.course_type %}
        <div class="form-row">
          {% form_control form.lecture_hours "col" %}
          {% form_control form.lab_work_hours "col" %}
        </div>
        <div class="form-row">
          {% form_control form.practice_hours "col" %}
          {% form_control form.student_hours "col" %}
        </div>
        <div class="form-row">
          {% form_control form.control_hours "col" %}
          {% form_control form.total_hours "col" %}
        </div>
      </div>
      <div class="col">
        {{ form.students|hidden }}
        <label>Студенты изучающие дисциплину</label>
        <div class="list-group" id="available_students">
          {% include 'course/students.html' %}
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <input type="submit" name="submit" class="btn btn-primary" value="Сохранить">
        {% if form.instance.pk %}
          <a href="{% url 'course:admin_delete' form.instance.id %}" class="btn btn-danger" role="button">Удалить</a>
        {% endif %}
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </div>
    </div>
  </form>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      // Пересчет суммы часов
      function calculateTotalHours() {
        $('#id_total_hours').val(
          parseInt($('#id_lecture_hours').val()) +
          parseInt($('#id_lab_work_hours').val()) +
          parseInt($('#id_practice_hours').val()) +
          parseInt($('#id_student_hours').val()) +
          parseInt($('#id_control_hours').val())
        );
      }

      // Вернуться назад, при нажатии кнопки назад
      $('#back').on('click', function () {
        history.back();
      });

      // При изменении часов нужно вызвать пересчет суммы часов
      $('#id_total_hours').attr('readonly', true);
      $('#id_lecture_hours').on('input', calculateTotalHours);
      $('#id_lab_work_hours').on('input', calculateTotalHours);
      $('#id_practice_hours').on('input', calculateTotalHours);
      $('#id_student_hours').on('input', calculateTotalHours);
      $('#id_control_hours').on('input', calculateTotalHours);

      // При выборе студента нужно выделить его в списке и убедиться, что данные будут сохранены
      $('a.list-group-item.list-group-item-action').on('click', function () {
        $(this).toggleClass('active');
        let active = $(this).hasClass('active');
        let studentId = $(this).data('id');
        $('select#id_students option[value="' + studentId + '"]').prop('selected', active);
      });

      // Загрузить список доступных студентов
      function initiateLoadAvailableStudents() {
        let course = {% if form.instance.pk %}{{ form.instance.id }}{% else %}''{% endif %};
        let semester = $(this).val();
        let $slot = $('#available_students');
        $slot.html(`
          <div class="progress">
            <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 100%"></div>
          </div>
        `);
        let url = '{% url 'course:admin_student' %}';
        if (semester !== '') {
          url = url + semester + '/';
          if (course !== '') {
            url = url + course + '/';
          }
          $slot.load(url);
        } else {
          $slot.html('');
        }
      }

      // При выборе семестра нужно заново загрузить список доступных студентов
      $('select#id_semester').on('change', initiateLoadAvailableStudents);
    });
  </script>
{% endblock %}

app_course/templates/course/list.html
{% extends 'base/menu.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Дисциплины</h1>
      {% regroup course_list by semester as semester_list %}
      {% for semester in semester_list %}
        <h3>{{ semester.grouper }}</h3>
        <ul>
          {% for course in semester.list %}
            <li><a href="{% url 'course:admin_edit' course.id %}">{{ course }}</a></li>
          {% endfor %}
        </ul>
      {% endfor %}
      <a href="{% url 'course:admin_create' %}" class="btn btn-primary" role="button">Создать</a>
    </div>
  </div>
{% endblock %}

app_course/templates/course/list_teacher.html
{% extends 'base/menu.html' %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Преподаваемые дисциплины</h1>
      <table class="table table-hover">
        <thead>
        <tr>
          <th>Дисциплина</th>
          <th></th>
          <th></th>
        </tr>
        </thead>
        <tbody>
        {% for c in teaching_load %}
          <tr>
            <td><a href="{% url 'course:teacher_page' c.id %}">{{ c.name }}</a></td>
            <td></td>
            <td><a href="#"><i class="fas fa-save"></i></a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

app_course/templates/course/students.html
{% for student in students_available %}
  <a href="#" data-id="{{ student.id }}"
     class="list-group-item list-group-item-action{% if student in students_selected %} active{% endif %}">
    {{ student }}
  </a>
{% endfor %}