project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app_base import views as base_views
from app_course import views as course_views
from app_course_file import views as course_file_views
from app_course_test import views as course_test_views
from app_course_topic import views as course_topic_views
from app_semester import views as semester_views
from app_student_group import views as student_group_views
from app_student_status import views as student_status_views
from app_user import views as user_views

base_namespace = ([
    path('', base_views.IndexPage.as_view(), name='index'),
], 'base')

course_namespace = ([
    path('admin_list/', course_views.admin_list, name='admin_list'),
    path('admin_create/', course_views.admin_form, name='admin_create'),
    path('admin_edit/<int:course_pk>/', course_views.admin_form, name='admin_edit'),
    path('admin_delete/<int:course_pk>/', course_views.admin_delete, name='admin_delete'),
    path('admin_student/', course_views.admin_students, name='admin_student'),  # Don't use this URL
    path('admin_student/<int:semester_pk>/', course_views.admin_students, name='admin_student'),
    path('admin_student/<int:semester_pk>/<int:course_pk>/', course_views.admin_students, name='admin_student'),
    path('teacher_list/', course_views.teacher_list, name='teacher_list'),
    path('teacher_page/<int:course_pk>/', course_views.teacher_page, name='teacher_page'),
    path('student_list/', course_views.student_list, name='student_list'),
    path('student_page/<int:course_pk>/', course_views.student_page, name='student_page'),
], 'course')

course_file_namespace = ([
    path('create/<int:pk>/', course_file_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', course_file_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', course_file_views.Delete.as_view(), name='delete'),
], 'course_file')

course_test_namespace = ([
    path('test/<int:test_pk>/', course_test_views.test_page, name='test_page'),
], 'course_test')

course_topic_namespace = ([
    path('create/<int:course_pk>/', course_topic_views.topic_create, name='create'),
    path('edit/<int:topic_pk>/', course_topic_views.topic_form, name='edit'),
    path('page/<int:topic_pk>/', course_topic_views.topic_page, name='topic_page'),
    path('delete/<int:pk>/', course_topic_views.Delete.as_view(), name='delete'),
], 'course_topic')

semester_namespace = ([
    path('list/', semester_views.semester_list, name='list'),
    path('create/', semester_views.semester_form, name='create'),
    path('edit/<int:semester_pk>/', semester_views.semester_form, name='edit'),
    path('delete/<int:semester_pk>/', semester_views.semester_delete, name='delete'),
], 'semester')

student_group_namespace = ([
    path('list/', student_group_views.group_list, name='list'),
    path('create/', student_group_views.group_form, name='create'),
    path('edit/<int:group_pk>/', student_group_views.group_form, name='edit'),
    path('delete/<int:group_pk>/', student_group_views.group_delete, name='delete'),
], 'student_group')

student_status_namespace = ([
    path('create/<int:pk>/', student_status_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', student_status_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', student_status_views.Delete.as_view(), name='delete'),
], 'student_status')

user_namespace = ([
    path('login/', user_views.LoginPage.as_view(), name='login'),
    path('logout/', user_views.LogoutPage.as_view(), name='logout'),
    path('password/', user_views.PasswordChangePage.as_view(), name='change_password'),
    path('password/<int:user_id>/', user_views.SetPasswordPage.as_view(), name='set_password'),
    path('list/', user_views.List.as_view(), name='list'),
    path('create/', user_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', user_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', user_views.Delete.as_view(), name='delete'),
], 'user')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(base_namespace)),
    path('course/', include(course_namespace)),
    path('course_file/', include(course_file_namespace)),
    path('course_test/', include(course_test_namespace)),
    path('course_topic/', include(course_topic_namespace)),
    path('semester/', include(semester_namespace)),
    path('student_group/', include(student_group_namespace)),
    path('student_status/', include(student_status_namespace)),
    path('user/', include(user_namespace)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_course_file/models.py
from django.db import models

from app_course.models import CourseElement


class File(CourseElement):
    kind = 'file'

    file = models.FileField('файл')

    class Meta:
        verbose_name = 'загруженный файл'
        verbose_name_plural = 'загруженные файлы'

app_course_file/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, UpdateView

from app_course.models import Course
from app_course.views import teacher_required
from app_course_file.models import File


@method_decorator(teacher_required(Course), name='dispatch')
class Create(CreateView):
    fields = '__all__'
    model = File
    template_name = 'course_file/file_form.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['course'] = get_object_or_404(Course, pk=self.kwargs['pk'])
        return initial

    def form_valid(self, form):
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('course:teacher_page', args=[self.object.course.id])


@method_decorator(teacher_required(File), name='dispatch')
class Update(UpdateView):
    fields = '__all__'
    model = File
    template_name = 'course_file/file_form.html'

    def get_success_url(self):
        return reverse_lazy('course:teacher_page', args=[self.object.course.id])


@method_decorator(teacher_required(File), name='dispatch')
class Delete(DeleteView):
    model = File
    template_name = 'course_file/confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('course:teacher_page', args=[self.object.course.id])

app_course_file/templates/course_file/confirm_delete.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Удаление файла</h1>
      <p>Подтвердите удаление файла {{ object }}</p>
      <form method="post">
        {% csrf_token %}
        <input type="submit" name="submit" class="btn btn-danger" value="Удалить">
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function (event) {
        history.back();
      });
    });
  </script>
{% endblock %}

app_course_file/templates/course_file/file_form.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% load static %}
{% block title %}{{ file.code }} {{ file.name }}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>
        {% if form.instance.pk %}
          Редактирование файла
        {% else %}
          Создание файла
        {% endif %}
      </h1>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
        {{ form.course|hidden }}
        <div class="form-row">
          {% form_control form.order "col-2" %}
          {% form_control form.name "col-10" %}
        </div>
        <div class="custom-file mb-3">
          <input type="file" class="custom-file-input" id="id_file" name="file" required>
          <label class="custom-file-label" for="id_file">Выберите файл...</label>
          {% for e in form.file.errors %}
            <div class="invalid-feedback">{{ e }}</div>
          {% endfor %}
        </div>
        <input type="submit" name="submit" class="btn btn-primary" value="Сохранить">
        {% if form.instance.pk %}
          <a href="{% url 'course_file:delete' form.instance.id %}" class="btn btn-danger" role="button">Удалить</a>
        {% endif %}
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function () {
        history.back();
      });
    });
  </script>
{% endblock %}