project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from app_base import views as base_views
from app_course import views as course_views
from app_course_file import views as course_file_views
from app_course_test import views as course_test_views
from app_course_topic import views as course_topic_views
from app_semester import views as semester_views
from app_student_group import views as student_group_views
from app_student_status import views as student_status_views
from app_user import views as user_views

base_namespace = ([
    path('', base_views.IndexPage.as_view(), name='index'),
], 'base')

course_namespace = ([
    path('admin_list/', course_views.admin_list, name='admin_list'),
    path('admin_create/', course_views.admin_form, name='admin_create'),
    path('admin_edit/<int:course_pk>/', course_views.admin_form, name='admin_edit'),
    path('admin_delete/<int:course_pk>/', course_views.admin_delete, name='admin_delete'),
    path('admin_student/', course_views.admin_students, name='admin_student'),  # Don't use this URL
    path('admin_student/<int:semester_pk>/', course_views.admin_students, name='admin_student'),
    path('admin_student/<int:semester_pk>/<int:course_pk>/', course_views.admin_students, name='admin_student'),
    path('teacher_list/', course_views.teacher_list, name='teacher_list'),
    path('teacher_page/<int:course_pk>/', course_views.teacher_page, name='teacher_page'),
    path('student_list/', course_views.student_list, name='student_list'),
    path('student_page/<int:course_pk>/', course_views.student_page, name='student_page'),
], 'course')

course_file_namespace = ([
    path('create/<int:pk>/', course_file_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', course_file_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', course_file_views.Delete.as_view(), name='delete'),
], 'course_file')

course_test_namespace = ([
    path('test/<int:test_pk>/', course_test_views.test_page, name='test_page'),
], 'course_test')

course_topic_namespace = ([
    path('create/<int:course_pk>/', course_topic_views.topic_create, name='create'),
    path('edit/<int:topic_pk>/', course_topic_views.topic_form, name='edit'),
    path('page/<int:topic_pk>/', course_topic_views.topic_page, name='topic_page'),
    path('delete/<int:pk>/', course_topic_views.Delete.as_view(), name='delete'),
], 'course_topic')

semester_namespace = ([
    path('list/', semester_views.semester_list, name='list'),
    path('create/', semester_views.semester_form, name='create'),
    path('edit/<int:semester_pk>/', semester_views.semester_form, name='edit'),
    path('delete/<int:semester_pk>/', semester_views.semester_delete, name='delete'),
], 'semester')

student_group_namespace = ([
    path('list/', student_group_views.group_list, name='list'),
    path('create/', student_group_views.group_form, name='create'),
    path('edit/<int:group_pk>/', student_group_views.group_form, name='edit'),
    path('delete/<int:group_pk>/', student_group_views.group_delete, name='delete'),
], 'student_group')

student_status_namespace = ([
    path('create/<int:pk>/', student_status_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', student_status_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', student_status_views.Delete.as_view(), name='delete'),
], 'student_status')

user_namespace = ([
    path('login/', user_views.LoginPage.as_view(), name='login'),
    path('logout/', user_views.LogoutPage.as_view(), name='logout'),
    path('password/', user_views.PasswordChangePage.as_view(), name='change_password'),
    path('password/<int:user_id>/', user_views.SetPasswordPage.as_view(), name='set_password'),
    path('list/', user_views.List.as_view(), name='list'),
    path('create/', user_views.Create.as_view(), name='create'),
    path('edit/<int:pk>/', user_views.Update.as_view(), name='edit'),
    path('delete/<int:pk>/', user_views.Delete.as_view(), name='delete'),
], 'user')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(base_namespace)),
    path('course/', include(course_namespace)),
    path('course_file/', include(course_file_namespace)),
    path('course_test/', include(course_test_namespace)),
    path('course_topic/', include(course_topic_namespace)),
    path('semester/', include(semester_namespace)),
    path('student_group/', include(student_group_namespace)),
    path('student_status/', include(student_status_namespace)),
    path('user/', include(user_namespace)),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path('__debug__/', include(debug_toolbar.urls)))

    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_course_topic/models.py
from django.db import models

from app_course.models import CourseElement


class Topic(CourseElement):
    kind = 'topic'

    text = models.TextField('текст', blank=True)

    class Meta:
        verbose_name = 'тема'
        verbose_name_plural = 'темы'

app_course_topic/views.py
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView
from markdown import markdown

from app_course.models import Course
from app_course.views import teacher_required
from app_course_topic.models import Topic


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = '__all__'


# @method_decorator(teacher_required(Course), name='dispatch')
# class Create(CreateView):
#     fields = '__all__'
#     model = models.Topic
#     template_name = 'ruler/course_topic/topic_form.html'
#
#     def get_initial(self):
#         initial = super().get_initial()
#         initial['course'] = get_object_or_404(Course, pk=self.kwargs['pk'])
#         return initial
#
#     def get_success_url(self):
#         # return reverse_lazy('course:teacher_page', kwargs={'pk': self.object.course.id})
#         return reverse_lazy('course:teacher_page', args=[self.object.course.id])


@teacher_required(Course, key='course_pk')
def topic_create(request, course_pk):
    initials = {'course': get_object_or_404(Course, pk=course_pk)}
    if request.method == 'POST':
        form = TopicForm(request.POST, initial=initials)
        if form.is_valid():
            form.save()
            return redirect('course:teacher_page', course_pk=form.instance.course.id)
    else:
        form = TopicForm(initial=initials)
    return render(request, 'course_topic/topic_form.html', {'form': form})


# @method_decorator(teacher_required(models.Topic), name='dispatch')
# class Update(UpdateView):
#     fields = '__all__'
#     model = models.Topic
#     template_name = 'ruler/course_topic/topic_form.html'
#
#     def get_success_url(self):
#         # return reverse_lazy('course:teacher_page', kwargs={'pk': self.object.course.id})
#         return reverse_lazy('course:teacher_page', args=[self.object.course.id])


@teacher_required(Course, key='topic_pk')
def topic_form(request, topic_pk):
    topic = get_object_or_404(Topic, pk=topic_pk)
    if request.method == 'POST':
        form = TopicForm(request.POST, instance=topic)
        if form.is_valid():
            form.save()
            return redirect('course:teacher_page', course_pk=form.instance.course.id)
    else:
        form = TopicForm(instance=topic)
    return render(request, 'course_topic/topic_form.html', {'form': form})


@method_decorator(teacher_required(Topic), name='dispatch')
class Delete(DeleteView):
    model = Topic
    template_name = 'course_topic/confirm_delete.html'

    def get_success_url(self):
        # return reverse_lazy('course:teacher_page', kwargs={'pk': self.object.course.id})
        return reverse_lazy('course:teacher_page', args=[self.object.course.id])


@login_required
def topic_page(request, topic_pk):
    topic = get_object_or_404(Topic, pk=topic_pk)
    course = topic.course
    text = topic.text.replace('%~', '/media/courses/%d/%d' % (course.id, topic.id))
    return render(request, 'course_topic/topic_detail.html', {
        'topic': topic,
        'course': course,
        'markdown': markdown(text, extensions={'markdown.extensions.attr_list'})
    })

app_course_topic/templates/course_topic/confirm_delete.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>Удаление темы курса</h1>
      <p>Подтвердите удаление темы курса {{ object }}</p>
      <form method="post">
        {% csrf_token %}
        <input type="submit" name="submit" class="btn btn-danger" value="Удалить">
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script>
    $(function () {
      $('#back').on('click', function (event) {
        history.back();
      });
    });
  </script>
{% endblock %}

app_course_topic/templates/course_topic/topic_detail.html
{% extends 'base/menu.html' %}
{% load static %}
{% block title %}{{ topic.code }} {{ topic.name }}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      {{ markdown|safe }}
    </div>
  </div>
{% endblock %}

app_course_topic/templates/course_topic/topic_form.html
{% extends 'base/menu.html' %}
{% load custom_tags %}
{% load static %}
{% block title %}{{ topic.code }} {{ topic.name }}{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      <h1>
        {% if form.instance.pk %}
          Редактирование темы
        {% else %}
          Создание темы
        {% endif %}
      </h1>
      <form method="post">
        {% csrf_token %}
        {% if form.non_field_errors %}
          <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
              <p>{{ error }}</p>
            {% endfor %}
          </div>
        {% endif %}
        {{ form.course|hidden }}
        <div class="form-row">
          {% form_control form.order "col-2" %}
          {% form_control form.name "col-10" %}
        </div>
        {{ form.text|hidden }}
        <div class="form-group">
          <label for="editor">Текст</label>
          <div id="editor">{{ form.instance.text }}</div>
        </div>
        <input type="submit" name="submit" class="btn btn-primary" value="Сохранить">
        {% if form.instance.pk %}
          <a href="{% url 'course_topic:delete' form.instance.id %}" class="btn btn-danger" role="button">Удалить</a>
        {% endif %}
        <button class="btn btn-link" type="button" id="back">Отменить</button>
      </form>
    </div>
  </div>
{% endblock %}
{% block scripts %}
  <script src="{% static 'ruler/js/ace-min/ace.js' %}"></script>
  <script>
    $(function () {
      $('#back').on('click', function () {
        history.back();
      });

      let editor = ace.edit('editor', {
        fontSize: 14,
        maxLines: 10000,
        minLines: 10,
        mode: 'ace/mode/markdown',
        theme: 'ace/theme/chrome',
        showPrintMargin: false
      });
      editor.setStyle('form-control');
      editor.session.on('change', function (event) {
        $('#id_text').html(editor.getValue());
      });
    });
  </script>
{% endblock %}